// Mock data used as fallback when the API server is unavailable (e.g. Vercel demo)
// Based on actual crawled data from Newegg / Amazon

const CAT_GPU = { id: 'cat-1', name: 'GPU', slug: 'gpu' };
const CAT_CPU = { id: 'cat-2', name: 'CPU', slug: 'cpu' };
const CAT_RAM = { id: 'cat-3', name: 'RAM', slug: 'ram' };
const CAT_SSD = { id: 'cat-4', name: 'SSD', slug: 'ssd' };

export const MOCK_CATEGORIES = [CAT_GPU, CAT_CPU, CAT_RAM, CAT_SSD];

// ── Products (list view) ──────────────────────────────────────────────────────

export const MOCK_PRODUCTS = [
  // ── GPU (existing 4 + new 8) ───────────────────────────────────────────────
  {
    id: 'p-01',
    name: 'NVIDIA GeForce RTX 4090 24GB GDDR6X Founders Edition',
    brand: 'NVIDIA',
    slug: 'rtx-4090-founders-edition',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-126-753-01.jpg',
    lowestPrice: '1599.00',
    lowestCurrency: 'USD',
    previousLowestPrice: '1699.00',
    originalPrice: '1599.00',
    storeNames: 'Newegg, Amazon',
    category: CAT_GPU,
  },
  {
    id: 'p-02',
    name: 'NVIDIA GeForce RTX 4080 Super 16GB GDDR6X',
    brand: 'ASUS',
    slug: 'rtx-4080-super-16gb',
    imageUrl: 'https://m.media-amazon.com/images/I/81POeoI3lSL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '979.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '1099.99',
    originalPrice: '999.99',
    storeNames: 'Newegg, Amazon, B&H',
    category: CAT_GPU,
  },
  {
    id: 'p-03',
    name: 'AMD Radeon RX 7900 XTX 24GB GDDR6 Liquid Cooled',
    brand: 'AMD',
    slug: 'rx-7900-xtx-24gb',
    imageUrl: 'https://m.media-amazon.com/images/I/81huTBuLV+L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '849.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '979.99',
    originalPrice: null,
    storeNames: 'Amazon, Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-04',
    name: 'NVIDIA GeForce RTX 4070 Ti Super 16GB GDDR6X',
    brand: 'MSI',
    slug: 'rtx-4070-ti-super-16gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-931-05.jpg',
    lowestPrice: '769.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '849.99',
    originalPrice: '799.99',
    storeNames: 'Amazon, Newegg',
    category: CAT_GPU,
  },
  // new GPU 8
  {
    id: 'p-13',
    name: 'ASUS TUF Gaming GeForce RTX 5090 32GB GDDR7 OC Edition',
    brand: 'ASUS',
    slug: 'asus-tuf-rtx5090-32g-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-126-753-01.jpg',
    lowestPrice: '3799.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '3999.99',
    originalPrice: '3999.99',
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-14',
    name: 'MSI RTX 5070 12G Gaming Trio OC Graphics Card',
    brand: 'MSI',
    slug: 'msi-rtx5070-12g-gaming-trio-oc',
    imageUrl: 'https://m.media-amazon.com/images/I/71vOVP+iFnL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '679.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '749.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_GPU,
  },
  {
    id: 'p-15',
    name: 'ZOTAC SOLID CORE OC GeForce RTX 5080 16GB GDDR7',
    brand: 'ZOTAC',
    slug: 'zotac-rtx5080-16g-solid-core-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-500-604-02.jpg',
    lowestPrice: '1099.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '1199.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-16',
    name: 'GIGABYTE WindForce GeForce RTX 5070 Ti 16GB GDDR7',
    brand: 'GIGABYTE',
    slug: 'gigabyte-rtx5070ti-16g-windforce',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-932-771-02.jpg',
    lowestPrice: '849.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '899.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-17',
    name: 'MSI Gaming GeForce RTX 5070 Ti 16GB GDDR7 Gaming Trio OC',
    brand: 'MSI',
    slug: 'msi-rtx5070ti-16g-gaming-trio-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-931-05.jpg',
    lowestPrice: '879.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '929.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-18',
    name: 'MSI Suprim GeForce RTX 5090 32GB GDDR7 Liquid SOC',
    brand: 'MSI',
    slug: 'msi-rtx5090-32g-suprim-liquid-soc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-914-03.png',
    lowestPrice: '3499.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '3699.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-19',
    name: 'ASRock Steel Legend Radeon RX 9070 XT 16GB GDDR6',
    brand: 'ASRock',
    slug: 'asrock-rx9070xt-16g-steel-legend',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-930-136-05.jpg',
    lowestPrice: '579.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '629.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_GPU,
  },
  {
    id: 'p-20',
    name: 'ASUS Prime Radeon RX 9070 XT OC Edition 16GB',
    brand: 'ASUS',
    slug: 'asus-prime-rx9070xt-oc',
    imageUrl: 'https://m.media-amazon.com/images/I/81huTBuLV+L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '599.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '649.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_GPU,
  },

  // ── CPU (existing 3 + new 8) ───────────────────────────────────────────────
  {
    id: 'p-05',
    name: 'Intel Core i9-14900K 24-Core LGA1700 6.0GHz Desktop Processor',
    brand: 'Intel',
    slug: 'i9-14900k',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-505-08.jpg',
    lowestPrice: '519.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '589.99',
    originalPrice: null,
    storeNames: 'Amazon, B&H',
    category: CAT_CPU,
  },
  {
    id: 'p-06',
    name: 'AMD Ryzen 9 7950X3D 16-Core AM5 5.7GHz Desktop Processor',
    brand: 'AMD',
    slug: 'ryzen-9-7950x3d',
    imageUrl: 'https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '649.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '699.99',
    originalPrice: null,
    storeNames: 'Newegg, Amazon',
    category: CAT_CPU,
  },
  {
    id: 'p-07',
    name: 'Intel Core i7-14700K 20-Core LGA1700 5.6GHz Desktop Processor',
    brand: 'Intel',
    slug: 'i7-14700k',
    imageUrl: 'https://m.media-amazon.com/images/I/513c8GtpBBL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '349.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '419.99',
    originalPrice: null,
    storeNames: 'Amazon, Newegg, B&H',
    category: CAT_CPU,
  },
  // new CPU 8
  {
    id: 'p-21',
    name: 'AMD Ryzen 7 7800X3D 8-Core 16-Thread Desktop Processor',
    brand: 'AMD',
    slug: 'amd-ryzen-7-7800x3d',
    imageUrl: 'https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '384.00',
    lowestCurrency: 'USD',
    previousLowestPrice: '449.00',
    originalPrice: '449.00',
    storeNames: 'Amazon',
    category: CAT_CPU,
  },
  {
    id: 'p-22',
    name: 'Intel Core Ultra 9 285K Arrow Lake 24-Core LGA1851 125W',
    brand: 'Intel',
    slug: 'intel-core-ultra-9-285k',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-505-08.jpg',
    lowestPrice: '564.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '599.99',
    originalPrice: null,
    storeNames: 'Newegg, Amazon',
    category: CAT_CPU,
  },
  {
    id: 'p-23',
    name: 'Intel Core Ultra 7 265KF 20-Core Arrow Lake Desktop Processor',
    brand: 'Intel',
    slug: 'intel-core-ultra-7-265kf',
    imageUrl: 'https://m.media-amazon.com/images/I/513c8GtpBBL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '379.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '419.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_CPU,
  },
  {
    id: 'p-24',
    name: 'AMD Ryzen 9 9900X Granite Ridge (Zen 5) 12-Core AM5 4.4GHz',
    brand: 'AMD',
    slug: 'amd-ryzen-9-9900x',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-842-02.png',
    lowestPrice: '399.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '449.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_CPU,
  },
  {
    id: 'p-25',
    name: 'AMD Ryzen 5 5600 Vermeer (Zen 3) 6-Core 3.5GHz Socket AM4',
    brand: 'AMD',
    slug: 'amd-ryzen-5-5600',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-736-V03.jpg',
    lowestPrice: '109.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '129.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_CPU,
  },
  {
    id: 'p-26',
    name: 'Intel Core i5-12600KF Alder Lake 10-Core 3.7GHz LGA1700',
    brand: 'Intel',
    slug: 'intel-i5-12600kf',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-349-05.jpg',
    lowestPrice: '149.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '179.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_CPU,
  },
  {
    id: 'p-27',
    name: 'AMD Ryzen 5 5500 Cezanne (Zen 3) 6-Core 3.6GHz Socket AM4',
    brand: 'AMD',
    slug: 'amd-ryzen-5-5500',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-737-V03.jpg',
    lowestPrice: '89.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '109.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_CPU,
  },
  {
    id: 'p-28',
    name: 'Intel Core Ultra 9 285K 24-Core Desktop Processor',
    brand: 'Intel',
    slug: 'intel-core-ultra-9-285k-amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/51xxm7JkJ6L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '549.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '589.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_CPU,
  },

  // ── RAM (existing 2 + new 8) ───────────────────────────────────────────────
  {
    id: 'p-08',
    name: 'Corsair Vengeance DDR5-6000 32GB (2x16GB) CL30 Desktop Memory',
    brand: 'Corsair',
    slug: 'corsair-vengeance-ddr5-6000-32gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-941-08.jpg',
    lowestPrice: '84.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '109.99',
    originalPrice: null,
    storeNames: 'Amazon, Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-09',
    name: 'G.Skill Trident Z5 RGB DDR5-6400 64GB (2x32GB) CL32',
    brand: 'G.Skill',
    slug: 'gskill-trident-z5-ddr5-64gb',
    imageUrl: 'https://m.media-amazon.com/images/I/618SEnJR1nL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '164.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '199.99',
    originalPrice: null,
    storeNames: 'Newegg, Amazon',
    category: CAT_RAM,
  },
  // new RAM 8
  {
    id: 'p-29',
    name: 'CORSAIR VENGEANCE RGB DDR5 32GB (2x16GB) 6400MHz CL36',
    brand: 'Corsair',
    slug: 'corsair-vengeance-rgb-ddr5-6400-32gb',
    imageUrl: 'https://m.media-amazon.com/images/I/61D2DDpDITL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '109.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '129.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_RAM,
  },
  {
    id: 'p-30',
    name: 'CORSAIR Vengeance 32GB (2x16GB) DDR5 6000 Desktop Memory',
    brand: 'Corsair',
    slug: 'corsair-vengeance-ddr5-6000-32gb-nw',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-941-08.jpg',
    lowestPrice: '79.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '99.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-31',
    name: 'CORSAIR Vengeance RGB DDR5 6000 32GB (2x16GB) CL38',
    brand: 'Corsair',
    slug: 'corsair-vengeance-rgb-ddr5-6000-cl38',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-982-198-04.png',
    lowestPrice: '94.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '114.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-32',
    name: 'CORSAIR Vengeance RGB DDR5 6000 32GB CL30 Black',
    brand: 'Corsair',
    slug: 'corsair-vengeance-rgb-ddr5-6000-cl30',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-879-03.jpg',
    lowestPrice: '89.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '109.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-33',
    name: 'G.SKILL RipjawsV DDR4 32GB (2x16GB) 3200MT/s CL16',
    brand: 'G.Skill',
    slug: 'gskill-ripjawsv-ddr4-3200-32gb',
    imageUrl: 'https://m.media-amazon.com/images/I/618SEnJR1nL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '49.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '64.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_RAM,
  },
  {
    id: 'p-34',
    name: 'CORSAIR Vengeance LPX 16GB (2x8GB) DDR4 3200 Desktop Memory',
    brand: 'Corsair',
    slug: 'corsair-vengeance-lpx-ddr4-3200-16gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-540-S01.jpg',
    lowestPrice: '34.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '44.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-35',
    name: 'G.SKILL Ripjaws V 32GB (2x16GB) DDR4 3200 Desktop Memory',
    brand: 'G.Skill',
    slug: 'gskill-ripjaws-v-ddr4-3200-32gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-232-091-08.jpg',
    lowestPrice: '47.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '59.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_RAM,
  },
  {
    id: 'p-36',
    name: 'CORSAIR Vengeance DDR5 32GB (2x16GB) 6400MHz CL36 Gray',
    brand: 'Corsair',
    slug: 'corsair-vengeance-ddr5-6400-32gb-gray',
    imageUrl: 'https://m.media-amazon.com/images/I/718+JX81H6L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '104.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '119.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_RAM,
  },

  // ── SSD (existing 3 + new 8) ───────────────────────────────────────────────
  {
    id: 'p-10',
    name: 'Samsung 990 Pro 2TB NVMe M.2 PCIe 4.0 SSD 7450MB/s',
    brand: 'Samsung',
    slug: 'samsung-990-pro-2tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZL9Qpo1-L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '129.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '169.99',
    originalPrice: null,
    storeNames: 'Amazon, Newegg',
    category: CAT_SSD,
  },
  {
    id: 'p-11',
    name: 'WD Black SN850X 1TB NVMe M.2 PCIe 4.0 SSD 7300MB/s',
    brand: 'Western Digital',
    slug: 'wd-black-sn850x-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61MMxdpiUEL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '84.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '119.99',
    originalPrice: null,
    storeNames: 'Amazon, B&H',
    category: CAT_SSD,
  },
  {
    id: 'p-12',
    name: 'Crucial T700 4TB NVMe M.2 PCIe 5.0 SSD 12400MB/s',
    brand: 'Crucial',
    slug: 'crucial-t700-4tb',
    imageUrl: 'https://m.media-amazon.com/images/I/51WMvihHRvL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '269.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '349.99',
    originalPrice: null,
    storeNames: 'Newegg, Amazon',
    category: CAT_SSD,
  },
  // new SSD 8
  {
    id: 'p-37',
    name: 'Samsung 990 PRO SSD 1TB PCIe 4.0 M.2 NVMe 7450MB/s',
    brand: 'Samsung',
    slug: 'samsung-990-pro-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZL9Qpo1-L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '89.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '109.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_SSD,
  },
  {
    id: 'p-38',
    name: 'Crucial T710 PCIe Gen5 NVMe 2TB SSD Up to 14900MB/s',
    brand: 'Crucial',
    slug: 'crucial-t710-2tb',
    imageUrl: 'https://m.media-amazon.com/images/I/51WMvihHRvL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '249.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '299.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_SSD,
  },
  {
    id: 'p-39',
    name: 'Kingston NV3 1TB M.2 2280 NVMe SSD PCIe 4.0 6000MB/s',
    brand: 'Kingston',
    slug: 'kingston-nv3-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/71c5uuoM1bL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    lowestPrice: '59.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '74.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_SSD,
  },
  {
    id: 'p-40',
    name: 'Crucial P310 1TB M.2 2280 PCIe 4.0 NVMe 7100MB/s',
    brand: 'Crucial',
    slug: 'crucial-p310-1tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-156-411-01.jpg',
    lowestPrice: '64.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '79.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_SSD,
  },
  {
    id: 'p-41',
    name: 'SAMSUNG 870 EVO 4TB 2.5" SATA III Internal SSD',
    brand: 'Samsung',
    slug: 'samsung-870-evo-4tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-147-795-V01.jpg',
    lowestPrice: '199.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '249.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_SSD,
  },
  {
    id: 'p-42',
    name: 'Crucial BX500 2TB 3D NAND SATA 2.5" Internal SSD 540MB/s',
    brand: 'Crucial',
    slug: 'crucial-bx500-2tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-156-232-01.jpg',
    lowestPrice: '99.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '119.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_SSD,
  },
  {
    id: 'p-43',
    name: 'Western Digital 480GB WD Green Internal SSD SATA III',
    brand: 'Western Digital',
    slug: 'wd-green-480gb',
    imageUrl: 'https://m.media-amazon.com/images/I/61MMxdpiUEL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    lowestPrice: '34.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '44.99',
    originalPrice: null,
    storeNames: 'Amazon',
    category: CAT_SSD,
  },
  {
    id: 'p-44',
    name: 'SAMSUNG 990 EVO PLUS 4TB PCIe Gen4x4 / Gen5x2 M.2 7250MB/s',
    brand: 'Samsung',
    slug: 'samsung-990-evo-plus-4tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-147-901-02.jpg',
    lowestPrice: '229.99',
    lowestCurrency: 'USD',
    previousLowestPrice: '279.99',
    originalPrice: null,
    storeNames: 'Newegg',
    category: CAT_SSD,
  },
];

// ── Deals ─────────────────────────────────────────────────────────────────────

export const MOCK_DEALS = [
  {
    id: 'p-13',
    name: 'ASUS TUF Gaming GeForce RTX 5090 32GB GDDR7 OC Edition',
    brand: 'ASUS',
    slug: 'asus-tuf-rtx5090-32g-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-126-753-01.jpg',
    categoryName: 'GPU',
    categorySlug: 'gpu',
    currentPrice: '3799.99',
    previousPrice: '3999.99',
    originalPrice: '3999.99',
    currency: 'USD',
  },
  {
    id: 'p-21',
    name: 'AMD Ryzen 7 7800X3D 8-Core 16-Thread Desktop Processor',
    brand: 'AMD',
    slug: 'amd-ryzen-7-7800x3d',
    imageUrl: 'https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    categoryName: 'CPU',
    categorySlug: 'cpu',
    currentPrice: '384.00',
    previousPrice: '449.00',
    originalPrice: '449.00',
    currency: 'USD',
  },
  {
    id: 'p-29',
    name: 'CORSAIR VENGEANCE RGB DDR5 32GB (2x16GB) 6400MHz CL36',
    brand: 'Corsair',
    slug: 'corsair-vengeance-rgb-ddr5-6400-32gb',
    imageUrl: 'https://m.media-amazon.com/images/I/61D2DDpDITL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    categoryName: 'RAM',
    categorySlug: 'ram',
    currentPrice: '109.99',
    previousPrice: '129.99',
    originalPrice: null,
    currency: 'USD',
  },
  {
    id: 'p-38',
    name: 'Crucial T710 PCIe Gen5 NVMe 2TB SSD Up to 14900MB/s',
    brand: 'Crucial',
    slug: 'crucial-t710-2tb',
    imageUrl: 'https://m.media-amazon.com/images/I/51WMvihHRvL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    categoryName: 'SSD',
    categorySlug: 'ssd',
    currentPrice: '249.99',
    previousPrice: '299.99',
    originalPrice: null,
    currency: 'USD',
  },
  {
    id: 'p-14',
    name: 'MSI RTX 5070 12G Gaming Trio OC Graphics Card',
    brand: 'MSI',
    slug: 'msi-rtx5070-12g-gaming-trio-oc',
    imageUrl: 'https://m.media-amazon.com/images/I/71vOVP+iFnL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    categoryName: 'GPU',
    categorySlug: 'gpu',
    currentPrice: '679.99',
    previousPrice: '749.99',
    originalPrice: null,
    currency: 'USD',
  },
  {
    id: 'p-25',
    name: 'AMD Ryzen 5 5600 Vermeer (Zen 3) 6-Core 3.5GHz Socket AM4',
    brand: 'AMD',
    slug: 'amd-ryzen-5-5600',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-736-V03.jpg',
    categoryName: 'CPU',
    categorySlug: 'cpu',
    currentPrice: '109.99',
    previousPrice: '129.99',
    originalPrice: null,
    currency: 'USD',
  },
  {
    id: 'p-34',
    name: 'CORSAIR Vengeance LPX 16GB (2x8GB) DDR4 3200 Desktop Memory',
    brand: 'Corsair',
    slug: 'corsair-vengeance-lpx-ddr4-3200-16gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-540-S01.jpg',
    categoryName: 'RAM',
    categorySlug: 'ram',
    currentPrice: '34.99',
    previousPrice: '44.99',
    originalPrice: null,
    currency: 'USD',
  },
  {
    id: 'p-37',
    name: 'Samsung 990 PRO SSD 1TB PCIe 4.0 M.2 NVMe 7450MB/s',
    brand: 'Samsung',
    slug: 'samsung-990-pro-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZL9Qpo1-L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    categoryName: 'SSD',
    categorySlug: 'ssd',
    currentPrice: '89.99',
    previousPrice: '109.99',
    originalPrice: null,
    currency: 'USD',
  },
];

// ── Product detail pages ──────────────────────────────────────────────────────

const STORES = {
  newegg: { id: 'store-1', name: 'Newegg', logoUrl: 'https://c1.neweggimages.com/WebResource/Themes/Nest/logos/logo_424x210.png' },
  amazon: { id: 'store-2', name: 'Amazon', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg' },
  bh: { id: 'store-3', name: 'B&H', logoUrl: null },
};

export const MOCK_PRODUCT_DETAILS: Record<
  string,
  {
    id: string;
    name: string;
    brand: string;
    model: string;
    slug: string;
    imageUrl: string | null;
    description: string | null;
    specs: Record<string, unknown>;
    category: { name: string; slug: string };
    listings: {
      listingId: string;
      url: string;
      latestPrice: string | null;
      latestCurrency: string | null;
      latestOriginalPrice: string | null;
      inStock: boolean | null;
      store: { id: string; name: string; logoUrl: string | null };
    }[];
  }
> = {
  // ── GPU details ─────────────────────────────────────────────────────────────
  'rtx-4090-founders-edition': {
    id: 'p-01',
    name: 'NVIDIA GeForce RTX 4090 24GB GDDR6X Founders Edition',
    brand: 'NVIDIA',
    model: 'RTX 4090',
    slug: 'rtx-4090-founders-edition',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-126-753-01.jpg',
    description: 'The GeForce RTX 4090 is the flagship Ada Lovelace GPU. With 16,384 CUDA cores and 24GB GDDR6X, it delivers unmatched 4K gaming and creative performance.',
    specs: { 'GPU Architecture': 'Ada Lovelace', 'CUDA Cores': '16384', 'Memory': '24GB GDDR6X', 'Memory Bus': '384-bit', 'Boost Clock': '2.52 GHz', 'TDP': '450W' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-01-1', url: '#', latestPrice: '1599.00', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
      { listingId: 'l-01-2', url: '#', latestPrice: '1624.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'rtx-4080-super-16gb': {
    id: 'p-02',
    name: 'NVIDIA GeForce RTX 4080 Super 16GB GDDR6X',
    brand: 'ASUS',
    model: 'RTX 4080 Super',
    slug: 'rtx-4080-super-16gb',
    imageUrl: 'https://m.media-amazon.com/images/I/81POeoI3lSL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'The RTX 4080 Super delivers exceptional 4K performance with 10,240 CUDA cores and 16GB GDDR6X memory.',
    specs: { 'GPU Architecture': 'Ada Lovelace', 'CUDA Cores': '10240', 'Memory': '16GB GDDR6X', 'Memory Bus': '256-bit', 'Boost Clock': '2.55 GHz', 'TDP': '320W' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-02-1', url: '#', latestPrice: '979.99', latestCurrency: 'USD', latestOriginalPrice: '999.99', inStock: true, store: STORES.newegg },
      { listingId: 'l-02-2', url: '#', latestPrice: '994.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'rx-7900-xtx-24gb': {
    id: 'p-03',
    name: 'AMD Radeon RX 7900 XTX 24GB GDDR6 Liquid Cooled',
    brand: 'AMD',
    model: 'RX 7900 XTX',
    slug: 'rx-7900-xtx-24gb',
    imageUrl: 'https://m.media-amazon.com/images/I/81huTBuLV+L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: "AMD's flagship RDNA 3 GPU with 24GB GDDR6 and a built-in liquid cooler.",
    specs: { 'GPU Architecture': 'RDNA 3', 'Compute Units': '96', 'Memory': '24GB GDDR6', 'Memory Bus': '384-bit', 'Game Clock': '2.3 GHz', 'TDP': '355W' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-03-1', url: '#', latestPrice: '849.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-03-2', url: '#', latestPrice: '869.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'rtx-4070-ti-super-16gb': {
    id: 'p-04',
    name: 'NVIDIA GeForce RTX 4070 Ti Super 16GB GDDR6X',
    brand: 'MSI',
    model: 'RTX 4070 Ti Super',
    slug: 'rtx-4070-ti-super-16gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-931-05.jpg',
    description: 'The RTX 4070 Ti Super brings 16GB GDDR6X, delivering excellent 1440p and solid 4K gaming.',
    specs: { 'GPU Architecture': 'Ada Lovelace', 'CUDA Cores': '8448', 'Memory': '16GB GDDR6X', 'Boost Clock': '2.61 GHz', 'TDP': '285W' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-04-1', url: '#', latestPrice: '769.99', latestCurrency: 'USD', latestOriginalPrice: '799.99', inStock: true, store: STORES.amazon },
      { listingId: 'l-04-2', url: '#', latestPrice: '779.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'asus-tuf-rtx5090-32g-oc': {
    id: 'p-13',
    name: 'ASUS TUF Gaming GeForce RTX 5090 32GB GDDR7 OC Edition',
    brand: 'ASUS',
    model: 'TUF-RTX5090-O32G-GAMING',
    slug: 'asus-tuf-rtx5090-32g-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-126-753-01.jpg',
    description: 'ASUS TUF Gaming RTX 5090 with 32GB GDDR7, DLSS 4.0 and PCIe 5.0 for ultimate performance.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '32GB GDDR7', 'Interface': 'PCIe 5.0', 'DLSS': '4.0' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-13-1', url: 'https://www.newegg.com/p/N82E16814126753', latestPrice: '3799.99', latestCurrency: 'USD', latestOriginalPrice: '3999.99', inStock: true, store: STORES.newegg },
    ],
  },
  'msi-rtx5070-12g-gaming-trio-oc': {
    id: 'p-14',
    name: 'MSI RTX 5070 12G Gaming Trio OC Graphics Card',
    brand: 'MSI',
    model: 'RTX 5070 12G GAMING TRIO OC',
    slug: 'msi-rtx5070-12g-gaming-trio-oc',
    imageUrl: 'https://m.media-amazon.com/images/I/71vOVP+iFnL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'MSI RTX 5070 Gaming Trio OC with 12GB GDDR7, 192-bit, NVIDIA Blackwell architecture.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '12GB GDDR7', 'Memory Bus': '192-bit', 'Boost Clock': '2625 MHz' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-14-1', url: 'https://www.amazon.com/dp/B0DYFXGDJF', latestPrice: '679.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'zotac-rtx5080-16g-solid-core-oc': {
    id: 'p-15',
    name: 'ZOTAC SOLID CORE OC GeForce RTX 5080 16GB GDDR7',
    brand: 'ZOTAC',
    model: 'ZT-B50800J2-10P',
    slug: 'zotac-rtx5080-16g-solid-core-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-500-604-02.jpg',
    description: 'ZOTAC RTX 5080 with 16GB GDDR7 256-bit, DLSS 4.0, PCIe 5.0.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '16GB GDDR7', 'Memory Bus': '256-bit', 'Interface': 'PCIe 5.0 x16' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-15-1', url: 'https://www.newegg.com/p/N82E16814500604', latestPrice: '1099.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'gigabyte-rtx5070ti-16g-windforce': {
    id: 'p-16',
    name: 'GIGABYTE WindForce GeForce RTX 5070 Ti 16GB GDDR7',
    brand: 'GIGABYTE',
    model: 'GV-N507TWF3OC-16GD',
    slug: 'gigabyte-rtx5070ti-16g-windforce',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-932-771-02.jpg',
    description: 'GIGABYTE WindForce RTX 5070 Ti with triple-fan cooling and 16GB GDDR7.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '16GB GDDR7', 'Interface': 'PCIe 5.0' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-16-1', url: 'https://www.newegg.com/p/N82E16814932771', latestPrice: '849.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'msi-rtx5070ti-16g-gaming-trio-oc': {
    id: 'p-17',
    name: 'MSI Gaming GeForce RTX 5070 Ti 16GB GDDR7 Gaming Trio OC',
    brand: 'MSI',
    model: 'RTX 5070 Ti 16G GAMING TRIO OC',
    slug: 'msi-rtx5070ti-16g-gaming-trio-oc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-931-05.jpg',
    description: 'MSI Gaming Trio RTX 5070 Ti with 16GB GDDR7, PCIe 5.0.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '16GB GDDR7', 'Interface': 'PCIe 5.0' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-17-1', url: 'https://www.newegg.com/p/N82E16814137931', latestPrice: '879.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'msi-rtx5090-32g-suprim-liquid-soc': {
    id: 'p-18',
    name: 'MSI Suprim GeForce RTX 5090 32GB GDDR7 Liquid SOC',
    brand: 'MSI',
    model: 'RTX 5090 32G SUPRIM LIQUID SOC',
    slug: 'msi-rtx5090-32g-suprim-liquid-soc',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-137-914-03.png',
    description: 'MSI Suprim Liquid-cooled RTX 5090 with 32GB GDDR7, ultimate flagship.',
    specs: { 'GPU Architecture': 'Blackwell', 'Memory': '32GB GDDR7', 'Cooling': 'Liquid', 'Interface': 'PCIe 5.0' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-18-1', url: 'https://www.newegg.com/p/N82E16814137916', latestPrice: '3499.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'asrock-rx9070xt-16g-steel-legend': {
    id: 'p-19',
    name: 'ASRock Steel Legend Radeon RX 9070 XT 16GB GDDR6',
    brand: 'ASRock',
    model: 'RX9070XT SL 16G',
    slug: 'asrock-rx9070xt-16g-steel-legend',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/14-930-136-05.jpg',
    description: 'ASRock Steel Legend RX 9070 XT with 16GB GDDR6, PCIe 5.0.',
    specs: { 'GPU Architecture': 'RDNA 4', 'Memory': '16GB GDDR6', 'Interface': 'PCIe 5.0 x16' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-19-1', url: 'https://www.newegg.com/p/N82E16814930136', latestPrice: '579.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'asus-prime-rx9070xt-oc': {
    id: 'p-20',
    name: 'ASUS Prime Radeon RX 9070 XT OC Edition 16GB',
    brand: 'ASUS',
    model: 'PRIME-RX9070XT-O16G',
    slug: 'asus-prime-rx9070xt-oc',
    imageUrl: 'https://m.media-amazon.com/images/I/81huTBuLV+L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'ASUS Prime RX 9070 XT OC with Axial-tech fans, Dual BIOS, GPU Guard.',
    specs: { 'GPU Architecture': 'RDNA 4', 'Memory': '16GB GDDR6', 'Interface': 'PCIe 5.0' },
    category: { name: 'GPU', slug: 'gpu' },
    listings: [
      { listingId: 'l-20-1', url: 'https://www.amazon.com/dp/B0DRRMZDH6', latestPrice: '599.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },

  // ── CPU details ─────────────────────────────────────────────────────────────
  'i9-14900k': {
    id: 'p-05',
    name: 'Intel Core i9-14900K 24-Core LGA1700 6.0GHz Desktop Processor',
    brand: 'Intel',
    model: 'Core i9-14900K',
    slug: 'i9-14900k',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-505-08.jpg',
    description: "Intel's top-tier desktop CPU with 24 cores (8P+16E) and a max turbo boost of 6.0GHz.",
    specs: { 'Cores': '24 (8P + 16E)', 'Threads': '32', 'Max Turbo': '6.0 GHz', 'Socket': 'LGA1700', 'TDP': '125W' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-05-1', url: '#', latestPrice: '519.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-05-2', url: '#', latestPrice: '534.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.bh },
    ],
  },
  'ryzen-9-7950x3d': {
    id: 'p-06',
    name: 'AMD Ryzen 9 7950X3D 16-Core AM5 5.7GHz Desktop Processor',
    brand: 'AMD',
    model: 'Ryzen 9 7950X3D',
    slug: 'ryzen-9-7950x3d',
    imageUrl: 'https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: "AMD's 3D V-Cache flagship with 16 cores and 128MB stacked L3 cache.",
    specs: { 'Cores': '16', 'Threads': '32', 'Max Boost': '5.7 GHz', 'Socket': 'AM5', 'TDP': '120W', 'L3 Cache': '128MB' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-06-1', url: '#', latestPrice: '649.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
      { listingId: 'l-06-2', url: '#', latestPrice: '659.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'i7-14700k': {
    id: 'p-07',
    name: 'Intel Core i7-14700K 20-Core LGA1700 5.6GHz Desktop Processor',
    brand: 'Intel',
    model: 'Core i7-14700K',
    slug: 'i7-14700k',
    imageUrl: 'https://m.media-amazon.com/images/I/513c8GtpBBL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'The Core i7-14700K delivers 20-core performance at a mainstream price.',
    specs: { 'Cores': '20 (8P + 12E)', 'Threads': '28', 'Max Turbo': '5.6 GHz', 'Socket': 'LGA1700', 'TDP': '125W' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-07-1', url: '#', latestPrice: '349.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-07-2', url: '#', latestPrice: '354.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'amd-ryzen-7-7800x3d': {
    id: 'p-21',
    name: 'AMD Ryzen 7 7800X3D 8-Core 16-Thread Desktop Processor',
    brand: 'AMD',
    model: 'Ryzen 7 7800X3D',
    slug: 'amd-ryzen-7-7800x3d',
    imageUrl: 'https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'AMD 3D V-Cache gaming processor with 8 cores and 96MB L3 cache for ultimate gaming.',
    specs: { 'Cores': '8', 'Threads': '16', 'Max Boost': '5.0 GHz', 'Socket': 'AM5', 'TDP': '120W', 'L3 Cache': '96MB (3D V-Cache)' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-21-1', url: 'https://www.amazon.com/dp/B0BTZB7F88', latestPrice: '384.00', latestCurrency: 'USD', latestOriginalPrice: '449.00', inStock: true, store: STORES.amazon },
    ],
  },
  'intel-core-ultra-9-285k': {
    id: 'p-22',
    name: 'Intel Core Ultra 9 285K Arrow Lake 24-Core LGA1851 125W',
    brand: 'Intel',
    model: 'Core Ultra 9 285K',
    slug: 'intel-core-ultra-9-285k',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-505-08.jpg',
    description: 'Intel Arrow Lake flagship with 24 cores (8P+16E), LGA 1851 socket.',
    specs: { 'Cores': '24 (8P + 16E)', 'Max Turbo': '5.7 GHz', 'Socket': 'LGA1851', 'TDP': '125W', 'Cache': '40MB L3' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-22-1', url: 'https://www.newegg.com/p/N82E16819118505', latestPrice: '564.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
      { listingId: 'l-22-2', url: 'https://www.amazon.com/dp/B0DFKC99VL', latestPrice: '549.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'intel-core-ultra-7-265kf': {
    id: 'p-23',
    name: 'Intel Core Ultra 7 265KF 20-Core Arrow Lake Desktop Processor',
    brand: 'Intel',
    model: 'Core Ultra 7 265KF',
    slug: 'intel-core-ultra-7-265kf',
    imageUrl: 'https://m.media-amazon.com/images/I/513c8GtpBBL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Intel Arrow Lake 20-core desktop processor, 8P+12E cores, up to 5.5GHz.',
    specs: { 'Cores': '20 (8P + 12E)', 'Max Turbo': '5.5 GHz', 'Socket': 'LGA1851', 'TDP': '125W' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-23-1', url: 'https://www.amazon.com/dp/B0DFK2WHF8', latestPrice: '379.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'amd-ryzen-9-9900x': {
    id: 'p-24',
    name: 'AMD Ryzen 9 9900X Granite Ridge (Zen 5) 12-Core AM5 4.4GHz',
    brand: 'AMD',
    model: 'Ryzen 9 9900X',
    slug: 'amd-ryzen-9-9900x',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-842-02.png',
    description: 'AMD Zen 5 architecture with 12 cores and Radeon Graphics, 120W TDP.',
    specs: { 'Cores': '12', 'Threads': '24', 'Base Clock': '4.4 GHz', 'Socket': 'AM5', 'TDP': '120W', 'Architecture': 'Zen 5' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-24-1', url: 'https://www.newegg.com/p/N82E16819113842', latestPrice: '399.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'amd-ryzen-5-5600': {
    id: 'p-25',
    name: 'AMD Ryzen 5 5600 Vermeer (Zen 3) 6-Core 3.5GHz Socket AM4',
    brand: 'AMD',
    model: 'Ryzen 5 5600',
    slug: 'amd-ryzen-5-5600',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-736-V03.jpg',
    description: 'Zen 3 architecture 6-core processor with great single-threaded performance, AM4 socket.',
    specs: { 'Cores': '6', 'Threads': '12', 'Base Clock': '3.5 GHz', 'Socket': 'AM4', 'TDP': '65W', 'Architecture': 'Zen 3' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-25-1', url: 'https://www.newegg.com/p/N82E16819113736', latestPrice: '109.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'intel-i5-12600kf': {
    id: 'p-26',
    name: 'Intel Core i5-12600KF Alder Lake 10-Core 3.7GHz LGA1700',
    brand: 'Intel',
    model: 'Core i5-12600KF',
    slug: 'intel-i5-12600kf',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-118-349-05.jpg',
    description: 'Alder Lake 10-core (6P+4E), LGA 1700, 125W desktop processor.',
    specs: { 'Cores': '10 (6P + 4E)', 'Threads': '16', 'Base Clock': '3.7 GHz', 'Socket': 'LGA1700', 'TDP': '125W' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-26-1', url: 'https://www.newegg.com/p/N82E16819118349', latestPrice: '149.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'amd-ryzen-5-5500': {
    id: 'p-27',
    name: 'AMD Ryzen 5 5500 Cezanne (Zen 3) 6-Core 3.6GHz Socket AM4',
    brand: 'AMD',
    model: 'Ryzen 5 5500',
    slug: 'amd-ryzen-5-5500',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/19-113-737-V03.jpg',
    description: 'Cezanne Zen 3 budget 6-core processor, AM4 socket, 65W TDP.',
    specs: { 'Cores': '6', 'Threads': '12', 'Base Clock': '3.6 GHz', 'Socket': 'AM4', 'TDP': '65W', 'Architecture': 'Zen 3' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-27-1', url: 'https://www.newegg.com/p/N82E16819113737', latestPrice: '89.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'intel-core-ultra-9-285k-amazon': {
    id: 'p-28',
    name: 'Intel Core Ultra 9 285K 24-Core Desktop Processor',
    brand: 'Intel',
    model: 'Core Ultra 9 285K',
    slug: 'intel-core-ultra-9-285k-amazon',
    imageUrl: 'https://m.media-amazon.com/images/I/51xxm7JkJ6L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Intel flagship Arrow Lake processor with 24 cores, up to 5.7GHz unlocked, 40MB cache.',
    specs: { 'Cores': '24 (8P + 16E)', 'Threads': '24', 'Max Turbo': '5.7 GHz', 'Socket': 'LGA1851', 'TDP': '125W', 'Cache': '40MB' },
    category: { name: 'CPU', slug: 'cpu' },
    listings: [
      { listingId: 'l-28-1', url: 'https://www.amazon.com/dp/B0DFKC99VL', latestPrice: '549.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },

  // ── RAM details ─────────────────────────────────────────────────────────────
  'corsair-vengeance-ddr5-6000-32gb': {
    id: 'p-08',
    name: 'Corsair Vengeance DDR5-6000 32GB (2x16GB) CL30 Desktop Memory',
    brand: 'Corsair',
    model: 'CMK32GX5M2B6000C30',
    slug: 'corsair-vengeance-ddr5-6000-32gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-941-08.jpg',
    description: 'High-performance DDR5 kit tuned for Intel and AMD platforms. XMP 3.0 / EXPO compatible.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6000', 'Timings': 'CL30-36-36-76', 'Voltage': '1.35V' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-08-1', url: '#', latestPrice: '84.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-08-2', url: '#', latestPrice: '89.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'gskill-trident-z5-ddr5-64gb': {
    id: 'p-09',
    name: 'G.Skill Trident Z5 RGB DDR5-6400 64GB (2x32GB) CL32',
    brand: 'G.Skill',
    model: 'F5-6400J3239G32GX2-TZ5RK',
    slug: 'gskill-trident-z5-ddr5-64gb',
    imageUrl: 'https://m.media-amazon.com/images/I/618SEnJR1nL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'G.Skill flagship DDR5 kit with RGB lighting, 64GB total capacity.',
    specs: { 'Type': 'DDR5', 'Capacity': '64GB (2x32GB)', 'Speed': 'DDR5-6400', 'Timings': 'CL32-39-39-102', 'Voltage': '1.4V' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-09-1', url: '#', latestPrice: '164.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
      { listingId: 'l-09-2', url: '#', latestPrice: '169.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'corsair-vengeance-rgb-ddr5-6400-32gb': {
    id: 'p-29',
    name: 'CORSAIR VENGEANCE RGB DDR5 32GB (2x16GB) 6400MHz CL36',
    brand: 'Corsair',
    model: 'CMH32GX5M2B6400C36',
    slug: 'corsair-vengeance-rgb-ddr5-6400-32gb',
    imageUrl: 'https://m.media-amazon.com/images/I/61D2DDpDITL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Corsair Vengeance RGB DDR5 with Intel XMP 3.0, 6400MHz CL36.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6400', 'Timings': 'CL36-48-48-104', 'Voltage': '1.35V' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-29-1', url: 'https://www.amazon.com/dp/B0BXHC74WD', latestPrice: '109.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'corsair-vengeance-ddr5-6000-32gb-nw': {
    id: 'p-30',
    name: 'CORSAIR Vengeance 32GB (2x16GB) DDR5 6000 Desktop Memory',
    brand: 'Corsair',
    model: 'CMK32GX5M2F6000Z36',
    slug: 'corsair-vengeance-ddr5-6000-32gb-nw',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-941-08.jpg',
    description: 'Corsair Vengeance DDR5-6000, low-profile heatspreader design.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6000' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-30-1', url: 'https://www.newegg.com/p/N82E16820982286', latestPrice: '79.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'corsair-vengeance-rgb-ddr5-6000-cl38': {
    id: 'p-31',
    name: 'CORSAIR Vengeance RGB DDR5 6000 32GB (2x16GB) CL38',
    brand: 'Corsair',
    model: 'CMH32GX5M2N6000Z30',
    slug: 'corsair-vengeance-rgb-ddr5-6000-cl38',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-982-198-04.png',
    description: 'Corsair Vengeance RGB DDR5-6000 with dynamic RGB lighting.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6000', 'Timings': 'CL38' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-31-1', url: 'https://www.newegg.com/p/N82E16820982184', latestPrice: '94.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'corsair-vengeance-rgb-ddr5-6000-cl30': {
    id: 'p-32',
    name: 'CORSAIR Vengeance RGB DDR5 6000 32GB CL30 Black',
    brand: 'Corsair',
    model: 'CMH32GX5M2B6000C38',
    slug: 'corsair-vengeance-rgb-ddr5-6000-cl30',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-879-03.jpg',
    description: 'Corsair Vengeance RGB DDR5-6000 CL30 in black.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6000', 'Timings': 'CL30' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-32-1', url: 'https://www.newegg.com/p/N82E16820982128', latestPrice: '89.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'gskill-ripjawsv-ddr4-3200-32gb': {
    id: 'p-33',
    name: 'G.SKILL RipjawsV DDR4 32GB (2x16GB) 3200MT/s CL16',
    brand: 'G.Skill',
    model: 'F4-3200C16D-32GVK',
    slug: 'gskill-ripjawsv-ddr4-3200-32gb',
    imageUrl: 'https://m.media-amazon.com/images/I/618SEnJR1nL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'G.SKILL RipjawsV DDR4 kit, Intel/AMD compatible, U-DIMM.',
    specs: { 'Type': 'DDR4', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR4-3200', 'Timings': 'CL16-18-18-38', 'Voltage': '1.35V' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-33-1', url: 'https://www.amazon.com/dp/B0171GQR0C', latestPrice: '49.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'corsair-vengeance-lpx-ddr4-3200-16gb': {
    id: 'p-34',
    name: 'CORSAIR Vengeance LPX 16GB (2x8GB) DDR4 3200 Desktop Memory',
    brand: 'Corsair',
    model: 'CMK16GX4M2E3200C16',
    slug: 'corsair-vengeance-lpx-ddr4-3200-16gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-236-540-S01.jpg',
    description: 'Corsair Vengeance LPX DDR4-3200, low-profile for compact builds.',
    specs: { 'Type': 'DDR4', 'Capacity': '16GB (2x8GB)', 'Speed': 'DDR4-3200' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-34-1', url: 'https://www.newegg.com/p/N82E16820236540', latestPrice: '34.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'gskill-ripjaws-v-ddr4-3200-32gb': {
    id: 'p-35',
    name: 'G.SKILL Ripjaws V 32GB (2x16GB) DDR4 3200 Desktop Memory',
    brand: 'G.Skill',
    model: 'F4-3200C16D-32GVK',
    slug: 'gskill-ripjaws-v-ddr4-3200-32gb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-232-091-08.jpg',
    description: 'G.SKILL Ripjaws V DDR4-3200 32GB kit from Newegg.',
    specs: { 'Type': 'DDR4', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR4-3200' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-35-1', url: 'https://www.newegg.com/p/N82E16820232091', latestPrice: '47.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'corsair-vengeance-ddr5-6400-32gb-gray': {
    id: 'p-36',
    name: 'CORSAIR Vengeance DDR5 32GB (2x16GB) 6400MHz CL36 Gray',
    brand: 'Corsair',
    model: 'CMK32GX5M2B6400Z36',
    slug: 'corsair-vengeance-ddr5-6400-32gb-gray',
    imageUrl: 'https://m.media-amazon.com/images/I/718+JX81H6L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Corsair Vengeance DDR5-6400 in Gray, AMD EXPO and Intel XMP 3.0.',
    specs: { 'Type': 'DDR5', 'Capacity': '32GB (2x16GB)', 'Speed': 'DDR5-6400', 'Timings': 'CL36-48-48-104', 'Voltage': '1.35V' },
    category: { name: 'RAM', slug: 'ram' },
    listings: [
      { listingId: 'l-36-1', url: 'https://www.amazon.com/dp/B0DJW4PKY3', latestPrice: '104.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },

  // ── SSD details ─────────────────────────────────────────────────────────────
  'samsung-990-pro-2tb': {
    id: 'p-10',
    name: 'Samsung 990 Pro 2TB NVMe M.2 PCIe 4.0 SSD 7450MB/s',
    brand: 'Samsung',
    model: 'MZ-V9P2T0B/AM',
    slug: 'samsung-990-pro-2tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZL9Qpo1-L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: "Samsung's fastest consumer NVMe SSD with sequential reads up to 7450MB/s.",
    specs: { 'Interface': 'PCIe 4.0 x4, NVMe 2.0', 'Capacity': '2TB', 'Seq. Read': '7450 MB/s', 'Seq. Write': '6900 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-10-1', url: '#', latestPrice: '129.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-10-2', url: '#', latestPrice: '134.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'wd-black-sn850x-1tb': {
    id: 'p-11',
    name: 'WD Black SN850X 1TB NVMe M.2 PCIe 4.0 SSD 7300MB/s',
    brand: 'Western Digital',
    model: 'WDS100T2X0E',
    slug: 'wd-black-sn850x-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61MMxdpiUEL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: "WD's top gaming SSD with 7300MB/s sequential reads.",
    specs: { 'Interface': 'PCIe 4.0 x4, NVMe 1.4', 'Capacity': '1TB', 'Seq. Read': '7300 MB/s', 'Seq. Write': '6300 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-11-1', url: '#', latestPrice: '84.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
      { listingId: 'l-11-2', url: '#', latestPrice: '89.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.bh },
    ],
  },
  'crucial-t700-4tb': {
    id: 'p-12',
    name: 'Crucial T700 4TB NVMe M.2 PCIe 5.0 SSD 12400MB/s',
    brand: 'Crucial',
    model: 'CT4000T700SSD3',
    slug: 'crucial-t700-4tb',
    imageUrl: 'https://m.media-amazon.com/images/I/51WMvihHRvL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: "Crucial's PCIe 5.0 flagship — 12400MB/s sequential reads, 4TB capacity.",
    specs: { 'Interface': 'PCIe 5.0 x4, NVMe 2.0', 'Capacity': '4TB', 'Seq. Read': '12400 MB/s', 'Seq. Write': '11800 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-12-1', url: '#', latestPrice: '269.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
      { listingId: 'l-12-2', url: '#', latestPrice: '279.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'samsung-990-pro-1tb': {
    id: 'p-37',
    name: 'Samsung 990 PRO SSD 1TB PCIe 4.0 M.2 NVMe 7450MB/s',
    brand: 'Samsung',
    model: 'MZ-V9P1T0B/AM',
    slug: 'samsung-990-pro-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZL9Qpo1-L._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Samsung 990 PRO 1TB for high-end computing and gaming workstations.',
    specs: { 'Interface': 'PCIe 4.0 x4', 'Capacity': '1TB', 'Seq. Read': '7450 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-37-1', url: 'https://www.amazon.com/dp/B0BHJF2VRN', latestPrice: '89.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'crucial-t710-2tb': {
    id: 'p-38',
    name: 'Crucial T710 PCIe Gen5 NVMe 2TB SSD Up to 14900MB/s',
    brand: 'Crucial',
    model: 'CT2000T710SSD8-01',
    slug: 'crucial-t710-2tb',
    imageUrl: 'https://m.media-amazon.com/images/I/51WMvihHRvL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Crucial T710 PCIe Gen5 with up to 14,900 MB/s, for creatives and hardcore gamers.',
    specs: { 'Interface': 'PCIe 5.0 x4', 'Capacity': '2TB', 'Seq. Read': '14900 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-38-1', url: 'https://www.amazon.com/dp/B0F9XMYR15', latestPrice: '249.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'kingston-nv3-1tb': {
    id: 'p-39',
    name: 'Kingston NV3 1TB M.2 2280 NVMe SSD PCIe 4.0 6000MB/s',
    brand: 'Kingston',
    model: 'SNV3S/1000G',
    slug: 'kingston-nv3-1tb',
    imageUrl: 'https://m.media-amazon.com/images/I/71c5uuoM1bL._AC_SX300_SY300_QL70_FMwebp_.jpg',
    description: 'Kingston NV3 budget NVMe SSD, PCIe 4.0, up to 6000 MB/s.',
    specs: { 'Interface': 'PCIe 4.0 Gen 4x4', 'Capacity': '1TB', 'Seq. Read': '6000 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-39-1', url: 'https://www.amazon.com/dp/B0DBR3DZWG', latestPrice: '59.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'crucial-p310-1tb': {
    id: 'p-40',
    name: 'Crucial P310 1TB M.2 2280 PCIe 4.0 NVMe 7100MB/s',
    brand: 'Crucial',
    model: 'CT1000P310SSD8',
    slug: 'crucial-p310-1tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-156-411-01.jpg',
    description: 'Crucial P310 3D NAND NVMe SSD, up to 7100 MB/s.',
    specs: { 'Interface': 'PCIe 4.0 x4', 'Capacity': '1TB', 'Seq. Read': '7100 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-40-1', url: 'https://www.newegg.com/p/N82E16820156412', latestPrice: '64.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'samsung-870-evo-4tb': {
    id: 'p-41',
    name: 'SAMSUNG 870 EVO 4TB 2.5" SATA III Internal SSD',
    brand: 'Samsung',
    model: 'MZ-77E4T0B/AM',
    slug: 'samsung-870-evo-4tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-147-795-V01.jpg',
    description: 'Samsung 870 EVO SATA SSD with massive 4TB capacity.',
    specs: { 'Interface': 'SATA III 6 Gb/s', 'Form Factor': '2.5"', 'Capacity': '4TB', 'Seq. Read': '560 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-41-1', url: 'https://www.newegg.com/p/N82E16820147795', latestPrice: '199.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'crucial-bx500-2tb': {
    id: 'p-42',
    name: 'Crucial BX500 2TB 3D NAND SATA 2.5" Internal SSD 540MB/s',
    brand: 'Crucial',
    model: 'CT2000BX500SSD1',
    slug: 'crucial-bx500-2tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-156-232-01.jpg',
    description: 'Crucial BX500 budget SATA SSD, 3D NAND, 2TB capacity.',
    specs: { 'Interface': 'SATA III 6 Gb/s', 'Form Factor': '2.5"', 'Capacity': '2TB', 'Seq. Read': '540 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-42-1', url: 'https://www.newegg.com/p/N82E16820156232', latestPrice: '99.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
  'wd-green-480gb': {
    id: 'p-43',
    name: 'Western Digital 480GB WD Green Internal SSD SATA III',
    brand: 'Western Digital',
    model: 'WDS480G3G0A',
    slug: 'wd-green-480gb',
    imageUrl: 'https://m.media-amazon.com/images/I/61MMxdpiUEL._AC_SY300_SX300_QL70_FMwebp_.jpg',
    description: 'WD Green budget SATA SSD, 2.5"/7mm, up to 545 MB/s.',
    specs: { 'Interface': 'SATA III 6 Gb/s', 'Form Factor': '2.5"', 'Capacity': '480GB', 'Seq. Read': '545 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-43-1', url: 'https://www.amazon.com/dp/B09TN1VKZL', latestPrice: '34.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.amazon },
    ],
  },
  'samsung-990-evo-plus-4tb': {
    id: 'p-44',
    name: 'SAMSUNG 990 EVO PLUS 4TB PCIe Gen4x4 / Gen5x2 M.2 7250MB/s',
    brand: 'Samsung',
    model: 'MZ-V9S4T0B/AM',
    slug: 'samsung-990-evo-plus-4tb',
    imageUrl: 'https://c1.neweggimages.com/productimage/nb640/20-147-901-02.jpg',
    description: 'Samsung 990 EVO Plus with HMB Technology and Intelligent TurboWrite 2.0.',
    specs: { 'Interface': 'PCIe Gen4x4 / Gen5x2', 'Capacity': '4TB', 'Seq. Read': '7250 MB/s' },
    category: { name: 'SSD', slug: 'ssd' },
    listings: [
      { listingId: 'l-44-1', url: 'https://www.newegg.com/p/N82E16820147901', latestPrice: '229.99', latestCurrency: 'USD', latestOriginalPrice: null, inStock: true, store: STORES.newegg },
    ],
  },
};

// ── Price history generator (deterministic) ───────────────────────────────────

interface PriceRecord {
  price: string;
  recordedAt: string;
  store: { id: string; name: string };
}

function wave(day: number, seed: number): number {
  return Math.sin(day * 0.38 + seed) * 0.5 + Math.sin(day * 0.13 + seed * 1.7) * 0.5;
}

export function getMockPriceHistory(slug: string): PriceRecord[] {
  const detail = MOCK_PRODUCT_DETAILS[slug];
  if (!detail) return [];

  const records: PriceRecord[] = [];
  const now = new Date('2026-03-27T12:00:00Z');

  for (const listing of detail.listings) {
    if (!listing.latestPrice) continue;
    const basePrice = parseFloat(listing.latestPrice);
    const seed = listing.store.id.charCodeAt(listing.store.id.length - 1);

    for (let day = 30; day >= 0; day--) {
      const date = new Date(now);
      date.setDate(date.getDate() - day);
      const variance = wave(day, seed) * basePrice * 0.04;
      const price = (basePrice + variance + (day > 20 ? basePrice * 0.05 : 0)).toFixed(2);
      records.push({
        price,
        recordedAt: date.toISOString(),
        store: { id: listing.store.id, name: listing.store.name },
      });
    }
  }

  return records;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getMockProductsResponse(params: {
  search: string;
  categoryId: string;
  minPrice: string;
  maxPrice: string;
  page: string;
  limit: number;
}) {
  let filtered = MOCK_PRODUCTS as typeof MOCK_PRODUCTS;

  if (params.search) {
    const q = params.search.toLowerCase();
    filtered = filtered.filter(
      (p) => p.name.toLowerCase().includes(q) || p.brand.toLowerCase().includes(q),
    );
  }
  if (params.categoryId) {
    filtered = filtered.filter((p) => p.category.id === params.categoryId);
  }
  if (params.minPrice) {
    const min = parseFloat(params.minPrice);
    filtered = filtered.filter((p) => p.lowestPrice && parseFloat(p.lowestPrice) >= min);
  }
  if (params.maxPrice) {
    const max = parseFloat(params.maxPrice);
    filtered = filtered.filter((p) => p.lowestPrice && parseFloat(p.lowestPrice) <= max);
  }

  const total = filtered.length;
  const pageNum = parseInt(params.page) || 1;
  const totalPages = Math.max(1, Math.ceil(total / params.limit));
  const start = (pageNum - 1) * params.limit;
  const data = filtered.slice(start, start + params.limit);

  return { data, meta: { total, page: pageNum, totalPages } };
}
